#--[ Форма предложения функции ]--#
name: Предложение
description: Новая функция или улучшение
title: "[фича] "
labels: [enhancement]
body:
  - type: textarea
    label: Проблема
    description: Какую задачу решает предложение и почему это важно
  - type: textarea
    label: Предлагаемое решение
    description: Как именно должна работать новая функция
  - type: textarea
    label: Альтернативы
    description: Другие способы решить ту же проблему, которые вы рассматривали
